/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CloudMusicUtils */

#ifndef _Included_CloudMusicUtils
#define _Included_CloudMusicUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CloudMusicUtils
 * Method:    initNativeDll
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CloudMusicUtils_initNativeDll
(JNIEnv*, jclass);

/*
 * Class:     CloudMusicUtils
 * Method:    getCloudMusicTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CloudMusicUtils_getCloudMusicTitle
(JNIEnv*, jclass);

/*
 * Class:     CloudMusicUtils
 * Method:    getCurrentPosition
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_CloudMusicUtils_getCurrentPosition
(JNIEnv*, jclass);

/*
 * Class:     CloudMusicUtils
 * Method:    nativeGc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CloudMusicUtils_nativeGc
(JNIEnv*, jclass);

#ifdef __cplusplus
}
#endif
#endif
